version: 2.1

orbs:
  codacy: codacy/base@1.0.0

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          cmd: sbt "set scalafmtUseIvy in ThisBuild := false;update"
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt "scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          cmd: |
            sbt +compile
            sbt +test:compile
          requires:
            - check_fmt
      - codacy/sbt:
          name: test
          cmd: |
            sbt "coverage;coverageReport;coverageAggregate"
            sbt +test

            if [ -z "$CODACY_PROJECT_TOKEN" ]; then
                echo "CODACY_PROJECT_TOKEN not found. Skipping send coverage to Codacy."
            else
                sbt codacyCoverage
            fi
          requires:
            - compile
      - codacy/sbt:
          name: publish
          cmd: |
            sbt "clean;retrieveGPGKeys"
            sbt "+publishSigned;sonatypeRelease"
          context: CodacyAWS
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          requires:
            - publish
